version: '3'
services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: moodle-db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=db_root_password
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=db_password
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - ./moodle_db:/var/lib/mysql

  moodle:
    build: .
    container_name: moodle
    restart: always
    ports:
      - "8080:8080"
      - "8444:8443"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=db_password
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb
