version: '3'
services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: moodle-db
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - ./moodle_db:/var/lib/mysql

  moodle:
    build: .
    container_name: moodle
    restart: always
    ports:
      - "8080:8080"
      - "8444:8443"
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=Admin
      - MOODLE_PASSWORD=
      - MOODLE_SMTP_HOST=
      - MOODLE_SMTP_PORT=
      - MOODLE_SMTP_USER=
      - MOODLE_SMTP_PASSWORD=
      - MOODLE_SMTP_PROTOCOL=tls
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb