version: '3'
services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: moodle-db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - ./moodle_db:/var/lib/mysql

  moodle:
    build: .
    container_name: moodle
    ports:
      - "8080:8080"
      - "8444:8443"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=bitnami
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=moises
      - MOODLE_PASSWORD=moises
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb