version: "3.8"

services:
  react-app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: react-app
    restart: always
    ports:
      - "8081:80"
    environment:
      - REACT_APP_SUPABASE_URL=https://api.uksaidiomas.com
      - REACT_APP_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      - REACT_APP_USER_TABLE=profile
      - REACT_APP_USER_BUCKET=profile
      - REACT_APP_USER_COURSES=user_courses
      - REACT_APP_WEB_BUCKET=website
    networks:
      - web-network
networks:
  web-network:
    driver: bridge
