version: "3.8"

services:
  react-app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: react-app
    restart: always
    ports:
      - "8081:80"
    env_file:
      - ../.env
    networks:
      - web-network
networks:
  web-network:
    driver: bridge
