version: "3.8"

services:
  api:
    build: .
    container_name: email-api
    restart: always
    env_file:
      - .env
    ports:
      - "2000:2000"
    environment:
      - PORT=2000
      - SECRET_KEY=
      - SMTP_SECURE=
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_USER=
      - SMTP_PASS=
      - ANON_USER=
      - ANON_KEY=
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "src/index.js"]
    networks:
      - web-network
networks:
  web-network:
    driver: bridge
