version: "3.8"

services:
  api:
    image: mailapi:1.0
    container_name: email-api
    restart: always
    ports:
      - "2000:2000"
    networks:
      - web-network
networks:
  web-network:
    driver: bridge
